# Site wide configuration

title: Alfred Spotify Mini Player
description: "Alfred workflow to control spotify like the built-in iTunes Mini Player"
logo: logo-default.jpg # 120x120 px default image used for Twitter summary card
teaser: teaser-default.jpg # 400x250 px default teaser image used in image archive grid
locale: en_US
#url: http://localhost:4000
url: http://alfred-spotify-mini-player.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap
  - jemoji

# prose
prose:
  siteurl: "http://alfred-spotify-mini-player.com"
  media: "images"
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          label: "Layout"
          element: "text"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "A awesome Headline!"

# Site owner
owner:
  name: "Vincent"
  email: alfred.spotify.mini.player@gmail.com
  twitter: "vdesabou"
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: alfred-spotify-mini-player


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
